# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='Ortopedista', max_length=50),
            preserve_default=False,
        ),
    ]
