# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('crm', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('cellPhone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(default=99999999999, max_length=11),
            preserve_default=False,
        ),
    ]
