# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170614_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ModeloExame'),
        ),
    ]
