# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170614_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nota',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
