# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_convenio_hospital_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='city',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='street',
        ),
    ]
