# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170626_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='hospital',
        ),
    ]
