# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170627_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='convenios',
            field=models.ManyToManyField(null=True, to='polls.Convenio'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Hospital'),
            preserve_default=False,
        ),
    ]
